CREATE OR REPLACE TABLE HOTEL.PUBLIC.Gold_AGG_Hotel_City_Sales
AS
SELECT  HOTEL_CITY,
        SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM HOTEL.PUBLIC.SILVER_HOTEL_BOOKING
GROUP BY HOTEL_CITY
ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM HOTEL.PUBLIC.Gold_AGG_Hotel_City_Sales;