CREATE OR REPLACE TABLE HOTEL.PUBLIC.Gold_AGG_Daily_Booking
AS
SELECT  CHECK_IN_DATE AS DATE,
        COUNT(*) AS TOTAL_BOOKING,
        SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
FROM HOTEL.PUBLIC.SILVER_HOTEL_BOOKING
GROUP BY CHECK_IN_DATE
ORDER BY DATE;

SELECT * FROM HOTEL.PUBLIC.Gold_AGG_Daily_Booking;