SELECT * FROM HOTEL.PUBLIC.BRONZE_HOTEL_BOOKING;


SELECT customer_email
FROM BRONZE_HOTEL_BOOKING
WHERE customer_email IS NULL
   OR customer_email NOT LIKE '%@%.%';


SELECT total_amount
FROM BRONZE_HOTEL_BOOKING
WHERE TRY_TO_NUMBER(total_amount) < 0;

SELECT CHECK_IN_DATE , CHECK_OUT_DATE
FROM BRONZE_HOTEL_BOOKING
WHERE TRY_TO_DATE(CHECK_IN_DATE) <  TRY_TO_DATE(CHECK_OUT_DATE);


SELECT DISTINCT BOOKING_STATUS
FROM BRONZE_HOTEL_BOOKING;

