INSERT INTO HOTEL.PUBLIC.SILVER_HOTEL_BOOKING
SELECT TRIM(BOOKING_ID) AS BOOKING_ID,
        TRIM(HOTEL_ID) AS HOTEL_ID,
        INITCAP(TRIM(HOTEL_CITY)) AS HOTEL_CITY,
        TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
        INITCAP(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
        CASE 
            WHEN CUSTOMER_EMAIL LIKE '%@%.%' THEN LOWER(TRIM(CUSTOMER_EMAIL))
            ELSE 'Not Specified'
        END AS CUSTOMER_EMAIL,
        TRY_TO_DATE(NULLIF(CHECK_IN_DATE,'')) AS CHECK_IN_DATE,
        TRY_TO_DATE(NULLIF(CHECK_OUT_DATE,'')) AS CHECK_OUT_DATE,
        INITCAP(TRIM(ROOM_TYPE)) AS ROOM_TYPE,
        TRY_TO_NUMBER(NUM_GUESTS) AS NUM_GUESTS,
        ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) AS TOTAL_AMOUNT,
        TRIM(CURRENCY) AS CURRENCY,
        CASE 
            WHEN LOWER(BOOKING_STATUS) IN ('confirmeeed','confirmd') THEN 'Confirmed'
            ELSE INITCAP(BOOKING_STATUS)
        END AS BOOKING_STATUS
FROM HOTEL.PUBLIC.BRONZE_HOTEL_BOOKING
WHERE TRY_TO_DATE(NULLIF(CHECK_IN_DATE, '')) IS NOT NULL
  AND TRY_TO_DATE(NULLIF(CHECK_OUT_DATE, '')) IS NOT NULL
  AND TRY_TO_DATE(NULLIF(CHECK_OUT_DATE, '')) >= TRY_TO_DATE(NULLIF(CHECK_IN_DATE, ''));